<?php

use Drupal\adback_solution_to_adblock\ApiSdk\AdbackSolutionToAdblockGeneric;
use Drupal\Core\Render\Markup;

function adback_solution_to_adblock_page_bottom(array &$page_bottom)
{
    $adback = AdbackSolutionToAdblockGeneric::getInstance();
    if ($adback->isConnected()) {
        $scripts = $adback->getScriptInfo();
        foreach ($scripts as $type => $script) {
            $page_bottom['adback_solution_to_adblock_' . $type] = [
                '#markup' => Markup::create('<script>' . $script . '</script>'),
            ];
        }
    }
}
